### ISSUE TITLE
SSR broken in 1.1.0

### ISSUE THREAD

**Issue by badtant** [theplatapi/react-disqus-thread#4]
My app is Universal and when i tried to upgrade from 1.0.3 to 1.1.0 rendering on the server broke.

ReferenceError: window is not defined
    at Object.<anonymous> (...node_modules/react-disqus-comments/build/components/DisqusThread.js:213:10)

**Comment by theplatapi** [comment]
Yup, that makes sense. The last update added references to the `window` object. I can try to fix it, but I don't have a test Universal app to run against so I won't be sure if it works. Do you have a sample Universal app with this package added that I can test with?

**Comment by jlobos** [comment]
@theplatapi sample: https://github.com/jlobos/blog

```js
ReferenceError: window is not defined
    at Object.<anonymous> (/home/j/io/blog/node_modules/react-disqus-comments/build/components/DisqusThread.js:213:10)
    at Module._compile (module.js:624:30)
    at Module._compile (/home/j/io/blog/node_modules/next/node_modules/source-map-support/source-map-support.js:492:25)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/j/io/blog/node_modules/react-disqus-comments/build/main.js:3:18)
```

**Comment by badtant** [comment]
Something like this seems to work

DisqusThread.defaultProps = {
    url: typeof window === 'undefined' ? null : window.location.href
};

**Comment by theplatapi** [comment]
@badtant Can you submit a pull request with the fix? It'd help me out a lot since you have a Universal app to run against as a test.
